### ISSUE TITLE
Block-scoped declarations (let, const, function, class) not yet supported outside strict

### ISSUE THREAD

**Issue by flangel** [IBM-Swift/Kitura#1197]
I am getting the following error when running **kitura init**

flx:kit2 flangel$ kitura init
/usr/local/Cellar/kitura/0.0.9/libexec/lib/node_modules/kitura-cli/kitura-init.js:6
let args = process.argv.slice(2);
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by flangel** [comment]
flx:kit2 flangel$ brew upgrade nodejs
Error: nodejs 9.3.0_1 already installed
flx:kit2 flangel$

**Comment by flangel** [comment]
Hi, I had the latest nodejs, but my link was to much older version of nodejs. Installing fresh using installer from nodejs website solved the issue.
